name: evopt
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10

  # Scientific computing & Data
  - numpy
  - pandas
  - scipy
  - scikit-learn

  # Plotting
  - matplotlib

  # Optimization
  - cvxpy

  # Geospatial
  - osmnx
  - geopandas 
  - networkx

  # Pip for packages not well-supported on conda-forge or for specific versions
  - pip
  - pip:
    - clarabel  # CVXPY recommends installing solvers via pip
    # Optional solvers, can be uncommented if direct control over their availability is desired
    # - osqp
    # - scs
    # - ecos
    # pyogrio can sometimes be a helpful geopandas backend if default has issues
    # - pyogrio 
